FROM node:20-alpine AS builder
WORKDIR /app
ENV NEXT_OUTPUT_MODE=standalone
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/ packages/
COPY apps/frontend/ apps/frontend/

RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @repo/frontend build

FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/apps/frontend/.next/standalone ./
COPY --from=builder /app/apps/frontend/.next/static ./.next/static
COPY --from=builder /app/apps/frontend/public ./public

EXPOSE 3000

CMD ["node", "server.js"]
